version: '3.3'
services:
  MACNSS:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
#    command:
#      - ALTER USER 'user'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:


#    docker-compose -f docker-compose.prod.yml up -d
